name: CI

on: [ push ]

jobs:
  api-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: PhpDocumentor
        uses: gpupo/actions-phpDocumentor@1.0
        with:
          dir: './'
#      - name: PhpDocumentor
#        run: |
#          wget https://phpdoc.org/phpDocumentor.phar
#          chmod +x phpDocumentor.phar
#          phpDocumentor.phar -t build -d src/
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build/api
